// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1pDCurzAS86lkwWuK0zplxHW0eRFIl4',
    appId: '1:362640334773:web:0967da040cd42c1f6c83fc',
    messagingSenderId: '362640334773',
    projectId: 'pushx-app',
    authDomain: 'pushx-app.firebaseapp.com',
    storageBucket: 'pushx-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAheqGoeWb3STLAhLkcDTGiyRHlNiGpvvM',
    appId: '1:362640334773:android:09a8fbddc03390da6c83fc',
    messagingSenderId: '362640334773',
    projectId: 'pushx-app',
    storageBucket: 'pushx-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLiK-3y253poyTY2sIPxBzmJWfwBeV_s',
    appId: '1:362640334773:ios:fc9bdbdb386d1bba6c83fc',
    messagingSenderId: '362640334773',
    projectId: 'pushx-app',
    storageBucket: 'pushx-app.firebasestorage.app',
    iosBundleId: 'com.example.pushup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbLiK-3y253poyTY2sIPxBzmJWfwBeV_s',
    appId: '1:362640334773:ios:fc9bdbdb386d1bba6c83fc',
    messagingSenderId: '362640334773',
    projectId: 'pushx-app',
    storageBucket: 'pushx-app.firebasestorage.app',
    iosBundleId: 'com.example.pushup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV1pDCurzAS86lkwWuK0zplxHW0eRFIl4',
    appId: '1:362640334773:web:ad5872dd511144236c83fc',
    messagingSenderId: '362640334773',
    projectId: 'pushx-app',
    authDomain: 'pushx-app.firebaseapp.com',
    storageBucket: 'pushx-app.firebasestorage.app',
  );
}
